ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "age" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "sameAsAbove" BOOLEAN;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "FormSubmission" ADD COLUMN IF NOT EXISTS "validationCode" TEXT;
